{"uuid": "17811c51-ce35-463f-a695-c75c872bcc2b", "children": ["1bcb8bcf-f685-433a-8524-d4072ee641a0"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: permission denied\n\n", "trace": "  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 936, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 795, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"c:\\Users\\Alex\\PycharmProjects\\Python_training\\conftest.py\", line 23, in app\n    fixture = Application(browser,target[\"web\"][\"baseUrl\"])\n  File \"c:\\Users\\Alex\\PycharmProjects\\Python_training\\fixture\\application.py\", line 14, in __init__\n    self.wd = webdriver.Firefox()\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 174, in __init__\n    keep_alive=True)\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1561565515296, "stop": 1561565519475}], "start": 1561565515296, "stop": 1561565519676}